### ISSUE TITLE
Plans to support u128 / i128 types

### ISSUE THREAD

**Issue by davidrusu** [3Hren/msgpack-rust#169]
Now that 128 bit integers are in stable rust, are there plans to support this type in msgpack?

**Comment by KillTheMule** [comment]
[The specification](https://github.com/msgpack/msgpack/blob/master/spec.md#int-format-family) does not mention 128 bit integers, so that might be the first place to ask about it, I guess.

**Comment by 3Hren** [comment]
Yes, @KillTheMule is right. And seems there is no place in current spec to support them, since the only single marker byte reserved is `0xc1`.

**Comment by vext01** [comment]
We could improve the error message? Currently if you try to serialise a `u128`, you get "syntax error", which is a bit cryptic.

**Comment by Rua** [comment]
I'm running into this when serialising random number generators. Their internal state uses `u128`, which triggers an error in RMP. I think that even if the MessagePack format doesn't natively support `u128`, it can still encode it in other ways such as a pair of `u64`, in order to be able to support more of the Serde data model.
