### ISSUE TITLE
rmp_serde::to_vec returns incorrect result if struct has `#[serde(flatten)]` attribute

### ISSUE THREAD

**Issue by gmoshkin** [3Hren/msgpack-rust#296]
```rust
fn main() {
    #[derive(serde::Serialize)]
    struct S {
        a: i32,
        #[serde(flatten)]
        s: T,
    }

    #[derive(serde::Serialize)]
    struct T {
        b: i32,
        c: i32,
    }

    #[derive(serde::Serialize)]
    struct U {
        a: i32,
        b: i32,
        c: i32,
    }

    let expected = to_vec_rmpv_value((1, 2, 3));

    let no_flatten = to_vec_rmpv_value(U { a: 1, b: 2, c: 3 });
    assert_eq!(no_flatten, expected);

    let flatten = to_vec_rmpv_value(S { a: 1, s: T { b: 2, c: 3 } });
    assert_eq!(flatten, expected); // this fails
}

fn to_vec_rmpv_value(v: impl serde::Serialize) -> rmpv::Value {
    let v = rmp_serde::to_vec(&v).unwrap();
    rmp_serde::from_read(&*v).unwrap()
}
```

Both assertions are expected to succeed, but instead the former one fails. The reason is the resulting message pack contains a map instead of an array even though `rmp_serde::to_vec` is used.

**Comment by Lucretiel** [comment]
This is a limitation of serde. When serde creates a `Deserialize` implementation for a "normal" struct, it silently allows structs to be Deserialized from both sequences and maps. You can see, in the expanded macro output for [this struct](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=acbf497e50791b8ebab05b707c6c427a) (Tools -> Expand Macros) that both a `visit_seq` and a `visit_map` method are generated for the `Visitor`.

On the other hand, when a `#[serde(flatten)]` type is involved, serde's options are more limited. Because the macro expansion doesn't have any visibility into the flattened type (`T`, in this case), it's forced to only generate `deserialize_map` type, and fall back to a less efficient implementation (involving buffering fields to be deserialized by the flattened field). 

Theoretically it *would* be possible for serde to generate a `visit_seq` for flattened fields; I can see how the `SeqAccess` could be forwarded to the inner type. In any case, though, this needs to be fixed in serde; there's not really anything rmp can do about it.
