### ISSUE TITLE
rmp-serde breaking change: unit enum variant used to be serialized as map with single key, now just a string

### ISSUE THREAD

**Issue by tfreiberg-fastly** [3Hren/msgpack-rust#310]
The changes in 5bf2c24203ad422233cf35b7b7bfad9f7e811814 seem to have changed the encoding format in a non-backwards compatible way (i.e. v0.15.5 can't decode data encoded by v1.1).
What do you think about making the behavior configurable, to enable a graceful migration? I could probably implement that if it helps

FYI, if other people have the same issue:
As a workaround, we're probably gonna use both v0.15.5 and v1.1 at the same time for a while, encoding with v0.15.5 and decoding with v1.1.

**Comment by kornelski** [comment]
I can accept a PR that makes it tolerate both encodings (fall back to the old one)

**Comment by kornelski** [comment]
Ah, I've assumed you've upgraded rmp and have old data to decode. But you mean using latest version to encode for 0.15 clients.

In such case I think using an older version for backwards-compatible encoding should be sufficient, and give you time to migrate everything to the latest version. So I'd rather not add encoding modes for this, since it's a one-off migration process.
