### ISSUE TITLE
Implement From trait for Value

### ISSUE THREAD

**Issue by dswd** [3Hren/msgpack-rust#60]
It would be much easier to work with values if you could just use primitive data types and have them converted automatically by the From trait.

**Comment by 3Hren** [comment]
Here https://github.com/3Hren/msgpack-rust/pull/61 I've implemented `From` trait for primitive numeric types. Not ready yet.

Initially I tried to do this more beauty using where clause, something like this:
```rust
impl<T> From<T> for Value
    where i64: From<T>
{
    fn from(v: T) -> Value {
        Value::Integer(Integer::I64(From::from(v)))
    }
}
```

But it results in trait conflicting between `i64: From<T>` and `u64: From<T>`, because there are core implementations for `From<u32> for i64` for example. Adding `Signed/Unsigned` traits didn't help.

Maybe you know how to deal with it?

**Comment by SuperFluffy** [comment]
It's not exactly the same as implementing `From`, but `serde_json` [implements][1] the very convient `to_value` and `from_value` helper functions to give you `Value`s by going through the `serialize` mechanism.

[1]: https://github.com/serde-rs/json/blob/master/json/src/value.rs#L989

**Comment by 3Hren** [comment]
Done in https://github.com/3Hren/msgpack-rust/pull/103. There are some `From` impls for `Value` as like as `to_value` generic function.
