### ISSUE TITLE
Deserialize strings and bytes without intermediate buffer with serde deserializer

### ISSUE THREAD

**Issue by knsd** [3Hren/msgpack-rust#75]
There is [buf](https://github.com/3Hren/msgpack-rust/blob/b0132f75882cc57c17f1e319ef07b99b0c94b8bc/rmp-serde/src/decode.rs#L203) field in `Deseralizer` which is used for strings and bytes deseralization: functions [read_str_data](https://github.com/3Hren/msgpack-rust/blob/b0132f75882cc57c17f1e319ef07b99b0c94b8bc/rmp/src/decode.rs#L1083) and [read_full](https://github.com/3Hren/msgpack-rust/blob/b0132f75882cc57c17f1e319ef07b99b0c94b8bc/rmp/src/decode.rs#L1359) takes a references to this buffer and `Deserializer`'s `R: Read`, read some bytes from `R: Read` and writes it to the buffer.

Looks like it's unnecessary overhead if `R` is `&[u8]` because it's possible to use this bytes directly from `&[u8]`.

I think it would be nice to have two different options:
1. deserialize from any generic `R: Read`, so we need in intermediate buffer,
2. deserialize from slice, without intermediate buffer.

**Comment by 3Hren** [comment]
Hmm, I need deeply investigate how Serde works. Are there any similar real-life examples for other protocols using serde?

**Comment by knsd** [comment]
> Are there any similar real-life examples for other protocols using serde?

Unfortunately I have not found any similar example. Checked `serde_cbor`, `serde_protobuf`, `serde-pickle`, `serde_json` and `bson` modules. They all use `Read` or `BufReader` or `Iterator<Item=u8>`.

**Comment by dtolnay** [comment]
@knsd yes serde_json uses `Iterator<Item=u8>` in the most general case but it is specialized (manually, not using `#![feature(specialization)]`) for `&[u8]` exactly as this ticket suggests. In fact we go a bit further and also specialize for `&str` which is even faster because the deserializer is allowed to assume the bytes are valid UTF-8.

Here is where the specialization happens: [json/src/de.rs](https://github.com/serde-rs/json/blob/146cf17f78c0a86801b10f0250e86d1078d5f450/json/src/de.rs#L1044-L1073)

Here is the trait backing those three different implementations: [`serde_json::read::Read`](https://github.com/serde-rs/json/blob/146cf17f78c0a86801b10f0250e86d1078d5f450/json/src/read.rs#L10)
